title: Nutchanon Buasuwan
description: |
  I am recent Statistics graduate, I have built a strong foundation in statistical modeling and machine learning. I have hands-on experience in applying Hierarchical Cluster Analysis (HCA) and hypothesis testing to generate data-driven insights from real-world datasets. I am highly motivated to leverage my analytical problem-solving skills to drive business performance and contribute to organizational success."<br>

  <a href="./assets/cv-nutchanon.pdf" target="_blank" style="color: #FFFFFF; font-weight: bold;">View CV</a>
theme: jekyll-theme-cayman
show_downloads: false
