title: <p align="center"> Nutchanon Buasuwan </p>

logo: "/assets/Pic.jpg"

description: |
  <p align="center">
    <a href="/pdf/CV.pdf">CV</a> |
    
  </p>

  <p align="justify">
    I am a recent Statistics graduate from the Faculty of Science with experience in applying statistical methods for data analysis and hypothesis testing.
theme: jekyll-theme-cayman

