title: Nutchanon Buasuwan
description: |
  I am a recent Statistics graduate from the Faculty of Science with experience in applying statistical methods for data analysis and hypothesis testing.

  <a href="./assets/cv-nutchanon.pdf" target="_blank" style="color: #FFFFFF; font-weight: bold;">View CV</a>
theme: jekyll-theme-cayman
show_downloads: false
